name: paydeuk-web CI/CD Pipeline

on:
  push:
    branches:
      - dev
      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2


      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.12.0

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Docker Build & Push
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/paydeuk_server_web .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/paydeuk_server_web

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Write PEM key from base64
        run: echo "${{ secrets.EC2_SSH_KEY_B64 }}" | base64 -d > key.pem

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key_path: key.pem         # ✅ 이걸 사용
          script: |
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/paydeuk_server_web
            docker stop paydeuk_server_web || true
            docker rm paydeuk_server_web || true
            docker run -d --name paydeuk_server_web -p 3000:3000 ${{ secrets.DOCKER_HUB_USERNAME }}/paydeuk_server_web

